import type { Lead } from './types';

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    name: 'Innovate Inc.',
    email: 'contact@innovate.com',
    phone: '+1 (555) 123-4567',
    website: 'https://innovate.com',
    tags: ['Tech', 'B2B', 'Hot Lead'],
  },
  {
    id: '2',
    name: 'DataDriven Co.',
    email: 'hello@datadriven.io',
    phone: '+44 20 7946 0958',
    website: 'https://datadriven.io',
    tags: ['SaaS', 'Analytics'],
  },
  {
    id: '3',
    name: 'Creative Solutions Ltd.',
    email: 'info@creativesolutions.co.uk',
    phone: '+44 161 496 0123',
    website: 'https://creativesolutions.co.uk',
    tags: ['Marketing', 'Agency'],
  },
  {
    id: '4',
    name: 'QuantumLeap Tech',
    email: 'press@quantumleap.tech',
    phone: '+1 (415) 555-0101',
    website: 'https://quantumleap.tech',
    tags: ['Deep Tech', 'R&D'],
  },
  {
    id: '5',
    name: 'GreenLeaf Organics',
    email: 'support@greenleaf.org',
    phone: '+1 (206) 555-0102',
    website: 'https://greenleaf.org',
    tags: ['E-commerce', 'Health'],
  },
  {
    id: '6',
    name: 'NextGen Robotics',
    email: 'sales@nextgenrobotics.com',
    phone: '+1 (617) 555-0103',
    website: 'https://nextgenrobotics.com',
    tags: ['Hardware', 'B2B'],
  },
  {
    id: '7',
    name: 'Fintech Futures',
    email: 'partners@fintechfutures.com',
    phone: '+44 20 8123 4567',
    website: 'https://fintechfutures.com',
    tags: ['Finance', 'High Priority'],
  },
];
